defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: promosite_development

test:
  <<: *defaults
  database: promosite_test

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: twiggzy
  #uri: <%= ENV['MONGOID_URI'] %>
  #connect = Mongoid.master.connection.connect_to_master 
  max_retries_on_connection_failure: 3
